[package]
name = "eg-2_20-minimal-rust-http-server-w-warp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3"
